# Generated by Django 3.2.10 on 2021-12-22 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.CreateModel(
            name='EventUser',
            fields=[
                ('created_at', models.DateField(auto_now_add=True)),
                ('time_created', models.TimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
