# Generated by Django 3.2.10 on 2021-12-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211221_2207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventuser',
            table='event_user',
        ),
    ]
