# Generated by Django 3.2.10 on 2021-12-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211227_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='numero',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
